# Generated by Django 2.0 on 2018-08-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_moteur_voitrue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voitrue',
            new_name='Voiture',
        ),
    ]
