# Generated by Django 2.0 on 2018-08-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180828_0018'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article_esp',
        ),
    ]
