# Generated by Django 2.0 on 2018-08-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180830_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='moteur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Moteur'),
        ),
    ]
