# Generated by Django 2.0 on 2018-09-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
