# Generated by Django 2.0 on 2018-09-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
